name: Packer build and Terraform deployment

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@main

      - name: Run 'packer init'
        run: "packer init ./packer/monitored-ami.pkr.hcl"

      - name: Run 'packer validate'
        run: "packer validate ./packer/monitored-ami.pkr.hcl"

      - name: Run 'packer build'
        run: "packer build ./packer/monitored-ami.pkr.hcl"

  terraform-deployment:
    runs-on: ubuntu-latest
    needs: packer-build

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}

      TF_VAR_grafana_endpoint: ${{ secrets.GRAFANA_ENDPOINT }}
      TF_VAR_grafana_user: ${{ secrets.GRAFANA_USER }}
      TF_VAR_grafana_password: ${{ secrets.GRAFANA_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Prepare backend file
        run: |
          sed "s/{{TF_CLOUD_ORGANIZATION}}/${TF_CLOUD_ORGANIZATION}/" ./terraform/backend.tf
          sed "s/{{TF_WORKSPACE}}/${TF_WORKSPACE}/" ./terraform/backend.tf

      - name: Terraform Deploy
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve