name: Packer build and Terraform deployment

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@main

      - name: Run 'packer init'
        run: "packer init ./packer/monitored-ami.pkr.hcl"

      - name: Run 'packer validate'
        run: "packer validate ./packer/monitored-ami.pkr.hcl"

      - name: Run 'packer build'
        run: "packer build ./packer/monitored-ami.pkr.hcl"

  terraform-deployment:
    runs-on: ubuntu-latest
    needs: packer-build

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Deploy
        run: |
          cd terraform
          terraform init
          terraform apply \
          -auto-approve \
          -var="grafana_endpoint=${{ secrets.GRAFANA_ENDPOINT }}" \
          -var="grafana_user=${{ secrets.GRAFANA_USER }}" \
          -var="grafana_password=${{ secrets.GRAFANA_PASSWORD }}"
